/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing
    jacoco
    alias(libs.plugins.sonarqube)
    id("org.ajoberstar.grgit") version "5.3.3"
    id("com.gradleup.shadow") version "9.3.1"
}

//val artifactoryBaseUrl: String by project
//val artifactoryRepo: String by project
//val artifactoryRepoUrl = "$artifactoryBaseUrl/$artifactoryRepo"
//val artifactoryUser: String by project
//val artifactoryPassword: String by project
val githubRepoName: String by project


// If publishing
//ext {
//    val grgit = org.ajoberstar.grgit.Grgit.open(mapOf("currentDir" to project.rootDir))
//    val branch = grgit.branch.current().name
//    // Assume this is a SNAPSHOT release if not on main
//    if (branch != "main") {
//        version = "$version-SNAPSHOT"
//    }
//}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // if artifactory or other artifact storage
//    maven {
//        url = uri("$artifactoryBaseUrl/gradle-remote")
//        content {
//            // this repository contains everything but private artifacts
//            excludeGroupByRegex("com\\.whatever\\..*")
//        }
//        credentials {
//            username = artifactoryUser
//            password = artifactoryPassword
//        }
//    }
//    maven {
//        url = uri(artifactoryRepoUrl)
//        content {
//            // this repository contains only private artifacts
//            includeGroupByRegex("com\\.whatever\\..*")
//        }
//        username = artifactoryUser
//        password = artifactoryPassword
//    }
//    maven {
//        url = uri("$artifactoryRepoUrl-snapshot")
//        content {
//            // this repository contains only private SNAPSHOT artifacts
//            includeGroupByRegex("com\\.whatever\\..*")
//        }
//        username = artifactoryUser
//        password = artifactoryPassword
//    }
}

dependencies {
    api(libs.jackson.databind)
    implementation(libs.log4j.core)
    implementation(libs.log4j.api)
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.pioneer)
}

tasks {
    test {
        useJUnitPlatform()
        finalizedBy(jacocoTestReport)
        jvmArgs("--add-opens", "java.base/java.lang=ALL-UNNAMED", "--add-opens", "java.base/java.util=ALL-UNNAMED")
    }

    jacocoTestReport {
        dependsOn(test)
        reports {
            xml.required.set(true)
        }
    }

    val sourcesJar = register<Jar>("sourcesJar") {
        from(sourceSets["main"].allJava)
        group = "build"
        description = "Creates the Sources JAR"
        archiveClassifier.set("sources")
    }

    val javadocJar = register<Jar>("javadocJar") {
        from(javadoc)
        group = "documentation"
        description = "Creates the Javadoc JAR"
        archiveClassifier.set("javadoc")
    }

    shadowJar {
        transform(Log4j2PluginsCacheFileTransformer::class.java)
        manifest {
            attributes["Multi-Release"] = true
        }
    }

    register("dist") {
        dependsOn(clean, jar, sourcesJar, javadocJar, shadowJar)
        group = "build"
        description = "Creates the JARs for classes, sources, and javadoc"
    }

    register("version") {
        group = "help"
        description = "Returns the value of the version property"
        println(version)
    }

    // Generate War File
//    val warArchive = named<War>("war") {
//        archiveFileName.set("temp.war")
//        dependsOn(webpack)
//    }

    // If using webpack
//    register<NpmTask>("webpack") {
//        args.set(listOf("run-script", "webpack"))
//        group = "npm"
//        dependsOn("npmInstall")
//        description = "Run webpack to install javascript and CSS dependencies"
//    }

    // If buiding locally to deploy to tomcat. Copy dependencies.
//    register<Copy>("copyDependencies") {
//        group = "build"
//        description = "Copy dependency from libraries to build output"
//        from(configurations.runtimeClasspath)
//        into(layout.buildDirectory.dir("lib"))
//    }

    // If building locally to deploy to tomcat. This uses the deploy.xml file.
//    register<Copy>("deployToTomcat") {
//        depndsOn(clean, war, "copyDependencies")
//        group = "build"
//        description = "Deploy to Tomcat"
//        from("${projectDir}/deploy.xml")
//        into(System.getenv("CATALINA_HOME") + "/conf/Catalina/localhost/")
//        expand(project.properties)
//        rename("(deploy)", project.name)
//    }

    // If needed to zip layer (dependencies) mainly for large lambda deployments in AWS
//    val zipLayer = register<Zip>("zipLayer") {
//        group = "build"
//        description = "Creates the Layer Zip for AWS Lambda"
//        archiveFileName = "${project.name}-layer-${version}.zip"
//        from(processResources)
//        into("java/lib") {
//            from(configurations.runtimeClasspath)
//            fileMode = 420
//        }
//        destinationDirectory = layout.buildDirectory.dir("libs")
//    }

    // If using db scripts for tests
//    processTestResources {
//        dependsOn("copyDbTestScripts")
//    }
//    register<GradleBuild>("buildDbScripts") {
//        group = "build"
//        description = "Performs tokenization on db scripts"
//        setDir("${layout.projectDirectory}/databases")
//        tasks = listOf("clean", "processProperties")
//    }
//    register<Sync>("copyDbTestScripts") {
//        dependsOn("buildDbScripts")
//        group = "verification"
//        description = "Copies db scripts to test resources"
//        includeEmptyDirs = false
//        from("${layout.projectDirectory}/databases/build/dist/db_script")
//        into("${layout.projectDirectory}/src/test/resources/databases")
//    }


    withType<JavaCompile> {
        options.encoding = "UTF-8"
    }
}


// If publishing
//publishing {
//    publications {
//        create<MavenPublication>("mavenJava") {
//            artifactId = project.name
//            from(components["java"])
//            artifact(tasks["sourcesJar"])
//            artifact(tasks["javadocJar"])
//            pom {
//                name.set(project.name)
//                description.set(project.description)
//                url.set("https://github.com/whatever/${githubRepoName}")
//                developers {
//                    developer {
//                        id.set("kevinhall")
//                        name.set("Kevin Hall")
//                        email.set("kevinsasa06@gmail.com")
//                    }
//                }
//                organization {
//                    name.set("Kevi Kev's Org")
//                    url.set("https://kevikev.org")
//                }
//                scm {
//                    connection.set("scm:git:git://github.com/whatever/${githubRepoName}.git")
//                    developerConnection.set("scm:git:ssh://github.com/whatever/${githubRepoName}.git")
//                    url.set("https://github.com/whatever/${githubRepoName}")
//                }
//            }
//        }
//    }
//    repositories {
//        maven {
//            // change URLs to point to repos
//            val releaseRepoUrl = uri(artifactoryRepoUrl)
//            val snapshotsRepoUrl = uri("${artifactoryRepoUrl}-snapshot")
//            url = if (version.toString().endsWith("-SNAPSHOT")) snapshotsRepoUrl else releaseRepoUrl
//            credentials {
//                username = artifactoryUser
//                password = artifactoryPassword
//            }
//        }
//    }
//}

configurations.all {
//    exclude(group = "junit")
//    exclude(group = "javax")
    // This allows you to reference -SNAPSHOT version of dependencies and not cache them.
    // Gradle automatically checks for new version of SNAPSHOT
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

defaultTasks(tasks["dist"])
