# Any of the properties below can be overridden by creating a gradle.properties file in your
# $USER_HOME/.gradle directory and adding your user-defined properties there.
# If you need to modify anything, that is the place to do it.
# You should only add properties that you need to override there, as they will take precedence over what is checked in
# and may cause issues with future builds if any of the properties in the repo are updated.
# See: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

name=java-encryption
description=A library for Encrypting/Decrypting Strings
group=com.kevikev.aws
version=0.0.1
githubRepoName=java-encryption

# Proxy Setup
# NOTICE: Setting the proxy makes the repos work on the internal network but breaks them elsewhere
# NOTICE: If you are seeing errors in IntelliJ, make sure proxy settings are manually set there as well.
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.proxyHost=
systemProp.https.proxyPort=
systemProp.https.nonProxyHosts=localhost|127.0.0.1
# certs.jks is a copy of the default Java Keystore (cacerts) with Root Certificates added
# Using this keystore allows Gradle to work behind the proxy server, which rewrites all SSL certificates
# NOTE: IntelliJ does not respect this setting. Initial installation of Gradle must be run from the commandline.
systemProp.javax.net.ssl.trustStore=
systemProp.javax.net.ssl.trustStorePassword=

# Add your Artifactory login information to $USER_HOME/.gradle/gradle.properties
# You can generate an identity token at:
artifactoryUser=
artifactoryPassword=
artifactoryBaseUrl=
artifactoryRepo=
org.gradle.caching=true
gradle.cache.push=false

